
const ActionTypes = {
  AUTH_LOGIN_REQUESTED: 'AUTH_LOGIN_REQUESTED',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_LOGIN_COMPLETED: 'AUTH_LOGIN_COMPLETED',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  AUTH_LOGOUT_REQUESTED: 'AUTH_LOGOUT_REQUESTED',
  AUTH_LOGOUT_COMPLETED: 'AUTH_LOGOUT_COMPLETED',
  GET_SCREEN_MENU_REQUESTED: 'GET_SCREEN_MENU_REQUESTED',
  GET_SCREEN_MENU_COMPLETED: 'GET_SCREEN_MENU_COMPLETED',
  GET_SCREEN_MENU_FAILED: 'GET_SCREEN_MENU_FAILED',
  GET_SCREEN_MENU_ERROR: 'GET_SCREEN_MENU_ERROR',
  GET_CATEGORY_REQUESTED: 'GET_CATEGORY_REQUESTED',
  GET_CATEGORY_COMPLETED: 'GET_CATEGORY_COMPLETED',
  GET_CATEGORY_FAILED: 'GET_CATEGORY_FAILED',
  GET_CATEGORY_ERROR: 'GET_CATEGORY_ERROR',
  CHANGE_CATEGORY_ACTIVE_INDEX: 'CHANGE_CATEGORY_ACTIVE_INDEX'
};
export default ActionTypes;
